
version: '3'

services:
 login_pwa:
   user: $UID:$GID
   build:
     context: .
   ports:
     - "8000:8000"
   volumes:
     - ./login_pwa:/login_pwa:Z
   stdin_open: true
   tty: true
   command: >
     sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runsslserver 0.0.0.0:8000"
